### Consulta el listado de usuarios
GET http://localhost:5000/users

### Consulta de un usuario por id(number)
GET http://localhost:5000/users/2

### Crear una nuevo usuario
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "ctorres",
  "email": "ct@gmail.com"
}

### Actualizacion un usuario por id
PUT http://localhost:5000/users/2
Content-Type: application/json

{
  "email": "ctorres@gmail.com"
}

### Eliminar un usuario por id
DELETE http://localhost:5000/users/2